# Generated by Django 3.2 on 2023-01-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_patient_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prescription Name')),
                ('size', models.IntegerField(verbose_name='Dosage(mg)')),
                ('prescribed', models.BooleanField(default=True, verbose_name='Currently Prescribed')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.doctor', verbose_name='Prescribing Doctor')),
            ],
        ),
    ]
