# Generated by Django 3.2 on 2023-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Dosage(mg)'),
        ),
    ]
