# Generated by Django 3.2 on 2023-01-10 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0019_auto_20230110_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(blank=True, choices=[('UH', 'UnitedHealth'), ('KF', 'Kaiser Foundation'), ('AI', 'Anthem Inc'), ('CC', 'Centene Corp'), ('HU', 'Humana'), ('CV', 'CVS'), ('HC', 'Health Care Service Corporation'), ('CH', 'Cigna  Health'), ('MH', 'Molina Healthcare'), ('IH', 'Independence Health Group')], max_length=2, null=True, verbose_name='Insurance Company')),
                ('subscriber', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('member', models.CharField(blank=True, max_length=20, verbose_name='Member ID')),
                ('group', models.CharField(blank=True, max_length=20, verbose_name='Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
